@Library('Shared') _
pipeline {
    agent { label "mynode" }

    tools {
        maven 'mvn'
    }

    environment {
        SONAR_HOME = tool 'sonar-scanner'
        NVD_API_KEY = credentials('NVD_API_KEY')
        AWS_ACCOUNT_ID = credentials('ACCOUNT_ID')
        AWS_ECR_REPO_NAME = credentials('ECR_REPOS3')
        AWS_DEFAULT_REGION = 'us-east-2'
        REPOSITORY_URI = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/"
        IMAGE_URI = "${REPOSITORY_URI}${AWS_ECR_REPO_NAME}:${BUILD_NUMBER}"
        GIT_REPO_NAME = "JenkinsCI-3-Tier-SpringBoot-piggymetrics"
    }

    stages {
        stage("Workspace cleanup"){
            steps{
                script{
                        cleanWs()
                    
                }
            }
        }
        
        stage('Git: Code Checkout') {
            steps {
                script{
                        code_checkout("https://github.com/hdxt25/JenkinsCI-3-Tier-SpringBoot-piggymetrics.git","main","GITHUB_CRED")
                    
                }
            }
        }

        stage('Build') {
            steps {
                dir('monitoring'){
                    sh 'mvn clean verify -DskipTests=true '  
                }
            }
        }

        // stage('Trivy File Scan') {
        //     steps {
        //         script{
        //             dir('monitoring'){
        //                 trivy_scan()
        //             }
        //         }                
        //     }
        // }

        // stage('OWASP Dependency-Check Scan') {
        //     steps {
        //         script{
        //             dir('monitoring'){
        //                 owasp_dependency()
        //             }
        //         }               
        //     }
        // }

        // stage('SonarQube: Code Analysis') {
        //     steps {
        //         script {
        //             dir('monitoring'){
        //                 mvn_sonarqube_analysis('sonar-server', 'piggymetrics-monitoring', 'piggymetrics-monitoring')
        //             }
        //         }
        //     }
        // }

        // stage('SonarQube: Code Quality Gates') {
        //     steps {
        //         script{
        //             dir('src'){
        //                sonarqube_code_quality()
        //             }
        //         }
        //     }
        // }
        

        stage("Docker Image multiarch build & push") {
            steps {
                script {
                    dir('monitoring'){
                        docker_multiarch_build("piggymetrics-monitoring","${env.BUILD_NUMBER}","hdxt25")
                    }
                }
            }
        }

        // stage("TRIVY Image Scan") {
        //     steps {
        //         script {
        //             dir('monitoring'){
        //                 trivy_multiarch_image_scan("piggymetrics-monitoring","${env.BUILD_NUMBER}","hdxt25") 
        //             }                  
        //         }
        //     }
        // } 

        stage("Update: Kubernetes manifest"){
            steps{
                script{
                    dir('kubernetes/backend'){
                        sh """
                            echo "Current BUILD_NUMBER: ${BUILD_NUMBER}"
                            sed -i "s|hdxt25/piggymetrics-monitoring:.*|hdxt25/piggymetrics-monitoring:${BUILD_NUMBER}|g" monitoring-deploy.yaml
                            echo "Updated image in manifest:"
                            grep -A 1 "image:" monitoring-deploy.yaml              
                        """
                    }
                }
            }
        }
        
        stage("Git: Code update and push to GitHub"){
            steps{
                script{
                    dir('kubernetes/backend'){
                        withCredentials([usernamePassword(
                                credentialsId: 'GITHUB_CRED', 
                                usernameVariable: 'GITHUB_USER_NAME', 
                                passwordVariable: 'GITHUB_TOKEN')]) {
                            sh """
                                git config user.email "hdxt25@gmail.com"
                                git config user.name "himanshu"
                        
                    
                                echo "Adding changes to git: "
                                git add monitoring-deploy.yaml
                        
                                echo "Commiting changes: "
                                git commit -m "Updated K8s Deployment Docker Image Version ${BUILD_NUMBER}" || echo "No changes to commit"
                        
                                echo "Pushing changes to github: "
                                git push https://${GITHUB_TOKEN}@github.com/${GITHUB_USER_NAME}/${env.GIT_REPO_NAME} HEAD:main
                            """
                        }    
                    }
                }
            }
        }
    }
}
